### PR TITLE
Allow newer dependencies, test newer GHC

### PR DESCRIPTION
**Pull request by ysangkok**

### CODE REVIEW

**Comment by ysangkok** [comment]
We should rerun this when 

* haskell-servant/servant#1714

has been released

**Comment by ysangkok** [comment]
@maksbotan Would it be possible for you to do the revisions for servant-js contained in this PR?

**Comment by maksbotan** [comment]
@ysangkok 9.8 CI still fails:

```
Error: cabal-3.10.2.0: Could not resolve dependencies:
[__0] trying: servant-js-0.9.4.2 (user goal)
[__1] trying: text-2.1/installed-1f8a (dependency of servant-js)
[__2] next goal: servant (dependency of servant-js)
[__2] rejecting: servant-0.20.1 (conflict: text => bytestring==0.12.0.2/installed-4571, servant => bytestring>=0.10.8.1 && <0.12)
```

Perhaps you need to bump `bytestring` on `servant` as well? Can you try it in this PR with `allow-newer`?

**Comment by ysangkok** [comment]
@maksbotan The issue is that bytestring was bumped in a [separate PR](https://github.com/haskell-servant/servant/pull/1711/files). It would be preferable if we also had revisions for all of these bumps. If we use allow-newer, it will only solve the issue in this package's CI suite.

**Comment by maksbotan** [comment]
Ah, I see. There were no Hackage revisions for that PR, let me fix that.

**Comment by maksbotan** [comment]
Revised on Hackage.

**Comment by ysangkok** [comment]
Thank you!

**Pull request merged**
